# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChenhLech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromcoin', models.IntegerField(default=0)),
                ('tocoin', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('fromexchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='general.Exchange')),
                ('toexchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='general.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('coinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.TypeCoin')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.User')),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='fromtypecoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='general.TypeCoin'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='totypecoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='general.TypeCoin'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.User'),
        ),
        migrations.AddField(
            model_name='coin',
            name='typecoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.TypeCoin'),
        ),
        migrations.AddField(
            model_name='chenhlech',
            name='fromtypecoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='general.TypeCoin'),
        ),
        migrations.AddField(
            model_name='chenhlech',
            name='totypecoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='general.TypeCoin'),
        ),
    ]
