# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
